// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_SUCCESS     PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCESS",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_SUCCESS":     2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_ALIPAY      PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_WECHAT      PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_BANK        PaymentMethod = 3
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_ALIPAY",
		2: "PAYMENT_METHOD_WECHAT",
		3: "PAYMENT_METHOD_BANK",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_ALIPAY":      1,
		"PAYMENT_METHOD_WECHAT":      2,
		"PAYMENT_METHOD_BANK":        3,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderNo       string                 `protobuf:"bytes,4,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=payment.PaymentMethod" json:"method,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,8,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	CreateAt      int64                  `protobuf:"varint,9,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,10,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentInfo) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaymentInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentInfo) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PaymentInfo) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentInfo) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentInfo) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *PaymentInfo) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type CreatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,5,opt,name=method,proto3,enum=payment.PaymentMethod" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePaymentReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentReq) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type CreatePaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PayUrl        string                 `protobuf:"bytes,2,opt,name=payUrl,proto3" json:"payUrl,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResp) Reset() {
	*x = CreatePaymentResp{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResp) ProtoMessage() {}

func (x *CreatePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResp.ProtoReflect.Descriptor instead.
func (*CreatePaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatePaymentResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *CreatePaymentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentReq) Reset() {
	*x = GetPaymentReq{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentReq) ProtoMessage() {}

func (x *GetPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentReq.ProtoReflect.Descriptor instead.
func (*GetPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentInfo           `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResp) Reset() {
	*x = GetPaymentResp{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResp) ProtoMessage() {}

func (x *GetPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResp.ProtoReflect.Descriptor instead.
func (*GetPaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentResp) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ListPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentReq) Reset() {
	*x = ListPaymentReq{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentReq) ProtoMessage() {}

func (x *ListPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentReq.ProtoReflect.Descriptor instead.
func (*ListPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListPaymentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPaymentReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PaymentInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentResp) Reset() {
	*x = ListPaymentResp{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentResp) ProtoMessage() {}

func (x *ListPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentResp.ProtoReflect.Descriptor instead.
func (*ListPaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentResp) GetList() []*PaymentInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListPaymentResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type NotifyPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPaymentReq) Reset() {
	*x = NotifyPaymentReq{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentReq) ProtoMessage() {}

func (x *NotifyPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentReq.ProtoReflect.Descriptor instead.
func (*NotifyPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyPaymentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotifyPaymentReq) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *NotifyPaymentReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type NotifyPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPaymentResp) Reset() {
	*x = NotifyPaymentResp{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaymentResp) ProtoMessage() {}

func (x *NotifyPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaymentResp.ProtoReflect.Descriptor instead.
func (*NotifyPaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyPaymentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"\xbf\x02\n" +
	"\vPaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderId\x18\x03 \x01(\x03R\aorderId\x12\x18\n" +
	"\aorderNo\x18\x04 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12.\n" +
	"\x06method\x18\x06 \x01(\x0e2\x16.payment.PaymentMethodR\x06method\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12$\n" +
	"\rtransactionId\x18\b \x01(\tR\rtransactionId\x12\x1a\n" +
	"\bcreateAt\x18\t \x01(\x03R\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\n" +
	" \x01(\x03R\bupdateAt\"\xa6\x01\n" +
	"\x10CreatePaymentReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x03R\aorderId\x12\x18\n" +
	"\aorderNo\x18\x03 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12.\n" +
	"\x06method\x18\x05 \x01(\x0e2\x16.payment.PaymentMethodR\x06method\"U\n" +
	"\x11CreatePaymentResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06payUrl\x18\x02 \x01(\tR\x06payUrl\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x1f\n" +
	"\rGetPaymentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x0eGetPaymentResp\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payment.PaymentInfoR\apayment\"P\n" +
	"\x0eListPaymentReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"Q\n" +
	"\x0fListPaymentResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.payment.PaymentInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"x\n" +
	"\x10NotifyPaymentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12$\n" +
	"\rtransactionId\x18\x03 \x01(\tR\rtransactionId\"-\n" +
	"\x11NotifyPaymentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x9f\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SUCCESS\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x04*~\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_METHOD_ALIPAY\x10\x01\x12\x19\n" +
	"\x15PAYMENT_METHOD_WECHAT\x10\x02\x12\x17\n" +
	"\x13PAYMENT_METHOD_BANK\x10\x032\xfe\x01\n" +
	"\aPayment\x12?\n" +
	"\x06Create\x12\x19.payment.CreatePaymentReq\x1a\x1a.payment.CreatePaymentResp\x126\n" +
	"\x03Get\x12\x16.payment.GetPaymentReq\x1a\x17.payment.GetPaymentResp\x129\n" +
	"\x04List\x12\x17.payment.ListPaymentReq\x1a\x18.payment.ListPaymentResp\x12?\n" +
	"\x06Notify\x12\x19.payment.NotifyPaymentReq\x1a\x1a.payment.NotifyPaymentRespB\vZ\t./paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payment_proto_goTypes = []any{
	(PaymentStatus)(0),        // 0: payment.PaymentStatus
	(PaymentMethod)(0),        // 1: payment.PaymentMethod
	(*PaymentInfo)(nil),       // 2: payment.PaymentInfo
	(*CreatePaymentReq)(nil),  // 3: payment.CreatePaymentReq
	(*CreatePaymentResp)(nil), // 4: payment.CreatePaymentResp
	(*GetPaymentReq)(nil),     // 5: payment.GetPaymentReq
	(*GetPaymentResp)(nil),    // 6: payment.GetPaymentResp
	(*ListPaymentReq)(nil),    // 7: payment.ListPaymentReq
	(*ListPaymentResp)(nil),   // 8: payment.ListPaymentResp
	(*NotifyPaymentReq)(nil),  // 9: payment.NotifyPaymentReq
	(*NotifyPaymentResp)(nil), // 10: payment.NotifyPaymentResp
}
var file_payment_proto_depIdxs = []int32{
	1,  // 0: payment.PaymentInfo.method:type_name -> payment.PaymentMethod
	0,  // 1: payment.PaymentInfo.status:type_name -> payment.PaymentStatus
	1,  // 2: payment.CreatePaymentReq.method:type_name -> payment.PaymentMethod
	2,  // 3: payment.GetPaymentResp.payment:type_name -> payment.PaymentInfo
	2,  // 4: payment.ListPaymentResp.list:type_name -> payment.PaymentInfo
	0,  // 5: payment.NotifyPaymentReq.status:type_name -> payment.PaymentStatus
	3,  // 6: payment.Payment.Create:input_type -> payment.CreatePaymentReq
	5,  // 7: payment.Payment.Get:input_type -> payment.GetPaymentReq
	7,  // 8: payment.Payment.List:input_type -> payment.ListPaymentReq
	9,  // 9: payment.Payment.Notify:input_type -> payment.NotifyPaymentReq
	4,  // 10: payment.Payment.Create:output_type -> payment.CreatePaymentResp
	6,  // 11: payment.Payment.Get:output_type -> payment.GetPaymentResp
	8,  // 12: payment.Payment.List:output_type -> payment.ListPaymentResp
	10, // 13: payment.Payment.Notify:output_type -> payment.NotifyPaymentResp
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
