// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通知渠道: 1-站内信 2-短信 3-邮件 4-推送
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_INBOX       Channel = 1
	Channel_CHANNEL_SMS         Channel = 2
	Channel_CHANNEL_EMAIL       Channel = 3
	Channel_CHANNEL_PUSH        Channel = 4
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_INBOX",
		2: "CHANNEL_SMS",
		3: "CHANNEL_EMAIL",
		4: "CHANNEL_PUSH",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_INBOX":       1,
		"CHANNEL_SMS":         2,
		"CHANNEL_EMAIL":       3,
		"CHANNEL_PUSH":        4,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

// 通知记录
type NotificationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Channel       Channel                `protobuf:"varint,5,opt,name=channel,proto3,enum=notification.Channel" json:"channel,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=isRead,proto3" json:"isRead,omitempty"`
	CreateAt      int64                  `protobuf:"varint,7,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationInfo) Reset() {
	*x = NotificationInfo{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationInfo) ProtoMessage() {}

func (x *NotificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationInfo.ProtoReflect.Descriptor instead.
func (*NotificationInfo) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationInfo) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *NotificationInfo) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationInfo) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

// 发送通知
type SendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Channel       Channel                `protobuf:"varint,4,opt,name=channel,proto3,enum=notification.Channel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReq) Reset() {
	*x = SendReq{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReq) ProtoMessage() {}

func (x *SendReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReq.ProtoReflect.Descriptor instead.
func (*SendReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendReq) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

type SendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResp) Reset() {
	*x = SendResp{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResp) ProtoMessage() {}

func (x *SendResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResp.ProtoReflect.Descriptor instead.
func (*SendResp) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取通知详情
type GetNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationReq) Reset() {
	*x = GetNotificationReq{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationReq) ProtoMessage() {}

func (x *GetNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationReq.ProtoReflect.Descriptor instead.
func (*GetNotificationReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *NotificationInfo      `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResp) Reset() {
	*x = GetNotificationResp{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResp) ProtoMessage() {}

func (x *GetNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResp.ProtoReflect.Descriptor instead.
func (*GetNotificationResp) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationResp) GetNotification() *NotificationInfo {
	if x != nil {
		return x.Notification
	}
	return nil
}

// 拉取某用户的通知列表
type ListByUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByUserReq) Reset() {
	*x = ListByUserReq{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByUserReq) ProtoMessage() {}

func (x *ListByUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByUserReq.ProtoReflect.Descriptor instead.
func (*ListByUserReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListByUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListByUserReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListByUserReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListByUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*NotificationInfo    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByUserResp) Reset() {
	*x = ListByUserResp{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByUserResp) ProtoMessage() {}

func (x *ListByUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByUserResp.ProtoReflect.Descriptor instead.
func (*ListByUserResp) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListByUserResp) GetList() []*NotificationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListByUserResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\"\xcf\x01\n" +
	"\x10NotificationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12/\n" +
	"\achannel\x18\x05 \x01(\x0e2\x15.notification.ChannelR\achannel\x12\x16\n" +
	"\x06isRead\x18\x06 \x01(\bR\x06isRead\x12\x1a\n" +
	"\bcreateAt\x18\a \x01(\x03R\bcreateAt\"\x82\x01\n" +
	"\aSendReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12/\n" +
	"\achannel\x18\x04 \x01(\x0e2\x15.notification.ChannelR\achannel\"4\n" +
	"\bSendResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"$\n" +
	"\x12GetNotificationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Y\n" +
	"\x13GetNotificationResp\x12B\n" +
	"\fnotification\x18\x01 \x01(\v2\x1e.notification.NotificationInfoR\fnotification\"O\n" +
	"\rListByUserReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"Z\n" +
	"\x0eListByUserResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.notification.NotificationInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total*k\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCHANNEL_INBOX\x10\x01\x12\x0f\n" +
	"\vCHANNEL_SMS\x10\x02\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x03\x12\x10\n" +
	"\fCHANNEL_PUSH\x10\x042\xe6\x01\n" +
	"\fNotification\x125\n" +
	"\x04Send\x12\x15.notification.SendReq\x1a\x16.notification.SendResp\x12V\n" +
	"\x0fGetNotification\x12 .notification.GetNotificationReq\x1a!.notification.GetNotificationResp\x12G\n" +
	"\n" +
	"ListByUser\x12\x1b.notification.ListByUserReq\x1a\x1c.notification.ListByUserRespB\x10Z\x0e./notificationb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notification_proto_goTypes = []any{
	(Channel)(0),                // 0: notification.Channel
	(*NotificationInfo)(nil),    // 1: notification.NotificationInfo
	(*SendReq)(nil),             // 2: notification.SendReq
	(*SendResp)(nil),            // 3: notification.SendResp
	(*GetNotificationReq)(nil),  // 4: notification.GetNotificationReq
	(*GetNotificationResp)(nil), // 5: notification.GetNotificationResp
	(*ListByUserReq)(nil),       // 6: notification.ListByUserReq
	(*ListByUserResp)(nil),      // 7: notification.ListByUserResp
}
var file_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationInfo.channel:type_name -> notification.Channel
	0, // 1: notification.SendReq.channel:type_name -> notification.Channel
	1, // 2: notification.GetNotificationResp.notification:type_name -> notification.NotificationInfo
	1, // 3: notification.ListByUserResp.list:type_name -> notification.NotificationInfo
	2, // 4: notification.Notification.Send:input_type -> notification.SendReq
	4, // 5: notification.Notification.GetNotification:input_type -> notification.GetNotificationReq
	6, // 6: notification.Notification.ListByUser:input_type -> notification.ListByUserReq
	3, // 7: notification.Notification.Send:output_type -> notification.SendResp
	5, // 8: notification.Notification.GetNotification:output_type -> notification.GetNotificationResp
	7, // 9: notification.Notification.ListByUser:output_type -> notification.ListByUserResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
