// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification.proto

package notification_client

import (
	"context"

	"github.com/fakerwjs/zero-demo/app/notification/rpc/notification"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetNotificationReq  = notification.GetNotificationReq
	GetNotificationResp = notification.GetNotificationResp
	ListByUserReq       = notification.ListByUserReq
	ListByUserResp      = notification.ListByUserResp
	NotificationInfo    = notification.NotificationInfo
	SendReq             = notification.SendReq
	SendResp            = notification.SendResp

	Notification interface {
		Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error)
		GetNotification(ctx context.Context, in *GetNotificationReq, opts ...grpc.CallOption) (*GetNotificationResp, error)
		ListByUser(ctx context.Context, in *ListByUserReq, opts ...grpc.CallOption) (*ListByUserResp, error)
	}

	defaultNotification struct {
		cli zrpc.Client
	}
)

func NewNotification(cli zrpc.Client) Notification {
	return &defaultNotification{
		cli: cli,
	}
}

func (m *defaultNotification) Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.Send(ctx, in, opts...)
}

func (m *defaultNotification) GetNotification(ctx context.Context, in *GetNotificationReq, opts ...grpc.CallOption) (*GetNotificationResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.GetNotification(ctx, in, opts...)
}

func (m *defaultNotification) ListByUser(ctx context.Context, in *ListByUserReq, opts ...grpc.CallOption) (*ListByUserResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.ListByUser(ctx, in, opts...)
}
