// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification.proto

package server

import (
	"context"

	"github.com/fakerwjs/zero-demo/app/notification/rpc/internal/logic"
	"github.com/fakerwjs/zero-demo/app/notification/rpc/internal/svc"
	"github.com/fakerwjs/zero-demo/app/notification/rpc/notification"
)

type NotificationServer struct {
	svcCtx *svc.ServiceContext
	notification.UnimplementedNotificationServer
}

func NewNotificationServer(svcCtx *svc.ServiceContext) *NotificationServer {
	return &NotificationServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationServer) Send(ctx context.Context, in *notification.SendReq) (*notification.SendResp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}

func (s *NotificationServer) GetNotification(ctx context.Context, in *notification.GetNotificationReq) (*notification.GetNotificationResp, error) {
	l := logic.NewGetNotificationLogic(ctx, s.svcCtx)
	return l.GetNotification(in)
}

func (s *NotificationServer) ListByUser(ctx context.Context, in *notification.ListByUserReq) (*notification.ListByUserResp, error) {
	l := logic.NewListByUserLogic(ctx, s.svcCtx)
	return l.ListByUser(in)
}
