// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AvatarResp struct {
	Url string `json:"url"`
}

type CreateOrderReq struct {
	Items []OrderItem `json:"items"`
}

type CreateOrderResp struct {
	Id      int64  `json:"id"`
	OrderNo string `json:"orderNo"`
	Success bool   `json:"success"`
}

type CreatePaymentReq struct {
	OrderId int64 `json:"orderId"`
	Amount  int64 `json:"amount"`
	Method  int32 `json:"method"`
}

type CreatePaymentResp struct {
	Id      int64  `json:"id"`
	PayUrl  string `json:"payUrl"`
	Success bool   `json:"success"`
}

type CreateProductReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Stock       int64  `json:"stock"`
	Image       string `json:"image"`
}

type CreateProductResp struct {
	Id      int64 `json:"id"`
	Success bool  `json:"success"`
}

type DeleteProductReq struct {
	Id int64 `path:"id"`
}

type DeleteProductResp struct {
	Success bool `json:"success"`
}

type GetNotificationReq struct {
	Id int64 `path:"id"`
}

type GetNotificationResp struct {
	Notification NotificationItem `json:"notification"`
}

type GetOrderReq struct {
	Id int64 `path:"id"`
}

type GetOrderResp struct {
	Order OrderInfo `json:"order"`
}

type GetPaymentReq struct {
	Id int64 `path:"id"`
}

type GetPaymentResp struct {
	Payment PaymentInfo `json:"payment"`
}

type GetProductReq struct {
	Id int64 `path:"id"`
}

type GetProductResp struct {
	Product ProductInfo `json:"product"`
}

type ListNotificationReq struct {
	Page int32 `form:"page,default=1"`
	Size int32 `form:"size,default=10"`
}

type ListNotificationResp struct {
	Total int64              `json:"total"`
	List  []NotificationItem `json:"list"`
}

type ListOrderReq struct {
	Page int32 `form:"page,default=1"`
	Size int32 `form:"size,default=10"`
}

type ListOrderResp struct {
	Total int64       `json:"total"`
	List  []OrderInfo `json:"list"`
}

type ListPaymentReq struct {
	Page int32 `form:"page,default=1"`
	Size int32 `form:"size,default=10"`
}

type ListPaymentResp struct {
	Total int64         `json:"total"`
	List  []PaymentInfo `json:"list"`
}

type ListProductReq struct {
	Page int32 `form:"page,default=1"`
	Size int32 `form:"size,default=10"`
}

type ListProductResp struct {
	Total int64         `json:"total"`
	List  []ProductInfo `json:"list"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id           int64  `json:"id"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type NotificationItem struct {
	Id       int64  `json:"id"`
	UserId   int64  `json:"userId"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Channel  int32  `json:"channel"`
	IsRead   bool   `json:"isRead"`
	CreateAt int64  `json:"createAt"`
}

type OrderInfo struct {
	Id         int64       `json:"id"`
	UserId     int64       `json:"userId"`
	OrderNo    string      `json:"orderNo"`
	TotalPrice int64       `json:"totalPrice"`
	Status     int32       `json:"status"`
	Items      []OrderItem `json:"items"`
	CreateAt   int64       `json:"createAt"`
	UpdateAt   int64       `json:"updateAt"`
}

type OrderItem struct {
	ProductId int64  `json:"productId"`
	Name      string `json:"name"`
	Price     int64  `json:"price"`
	Quantity  int64  `json:"quantity"`
}

type PaymentInfo struct {
	Id            int64  `json:"id"`
	UserId        int64  `json:"userId"`
	OrderId       int64  `json:"orderId"`
	OrderNo       string `json:"orderNo"`
	Amount        int64  `json:"amount"`
	Method        int32  `json:"method"`
	Status        int32  `json:"status"`
	TransactionId string `json:"transactionId"`
	CreateAt      int64  `json:"createAt"`
	UpdateAt      int64  `json:"updateAt"`
}

type ProductInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Stock       int64  `json:"stock"`
	Image       string `json:"image"`
	CreateAt    int64  `json:"createAt"`
	UpdateAt    int64  `json:"updateAt"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Mobile   string `json:"mobile"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
}

type SendNotificationReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Channel int32  `json:"channel"` // 1站内信 2短信 3邮件 4推送
}

type SendNotificationResp struct {
	Id      int64 `json:"id"`
	Success bool  `json:"success"`
}

type UpdateProductReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Stock       int64  `json:"stock"`
	Image       string `json:"image"`
}

type UpdateProductResp struct {
	Success bool `json:"success"`
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	CreateAt int64  `json:"createAt"`
}
