// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	notificationFieldNames          = builder.RawFieldNames(&Notification{})
	notificationRows                = strings.Join(notificationFieldNames, ",")
	notificationRowsExpectAutoSet   = strings.Join(stringx.Remove(notificationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	notificationRowsWithPlaceHolder = strings.Join(stringx.Remove(notificationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNotificationIdPrefix = "cache:notification:id:"
)

type (
	notificationModel interface {
		Insert(ctx context.Context, data *Notification) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Notification, error)
		Update(ctx context.Context, data *Notification) error
		Delete(ctx context.Context, id int64) error
	}

	defaultNotificationModel struct {
		sqlc.CachedConn
		table string
	}

	Notification struct {
		Id       int64     `db:"id"`
		UserId   int64     `db:"user_id"`   // 接收用户id
		Title    string    `db:"title"`     // 标题
		Content  string    `db:"content"`   // 内容
		Channel  int64     `db:"channel"`   // 渠道 1站内信 2短信 3邮件 4推送
		IsRead   int64     `db:"is_read"`   // 是否已读 0否 1是
		CreateAt time.Time `db:"create_at"` // 创建时间
		UpdateAt time.Time `db:"update_at"` // 更新时间
	}
)

func newNotificationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNotificationModel {
	return &defaultNotificationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`notification`",
	}
}

func (m *defaultNotificationModel) Delete(ctx context.Context, id int64) error {
	notificationIdKey := fmt.Sprintf("%s%v", cacheNotificationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, notificationIdKey)
	return err
}

func (m *defaultNotificationModel) FindOne(ctx context.Context, id int64) (*Notification, error) {
	notificationIdKey := fmt.Sprintf("%s%v", cacheNotificationIdPrefix, id)
	var resp Notification
	err := m.QueryRowCtx(ctx, &resp, notificationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notificationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNotificationModel) Insert(ctx context.Context, data *Notification) (sql.Result, error) {
	notificationIdKey := fmt.Sprintf("%s%v", cacheNotificationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, notificationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Content, data.Channel, data.IsRead)
	}, notificationIdKey)
	return ret, err
}

func (m *defaultNotificationModel) Update(ctx context.Context, data *Notification) error {
	notificationIdKey := fmt.Sprintf("%s%v", cacheNotificationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, notificationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Content, data.Channel, data.IsRead, data.Id)
	}, notificationIdKey)
	return err
}

func (m *defaultNotificationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNotificationIdPrefix, primary)
}

func (m *defaultNotificationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", notificationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNotificationModel) tableName() string {
	return m.table
}
