Name: product.rpc
ListenOn: ${PRODUCT_RPC_LISTEN:0.0.0.0:8006}
Etcd:
  Hosts:
    - ${ETCD_HOST:127.0.0.1}:${ETCD_PORT:2379}
  Key: product.rpc

DataSource: ${MYSQL_USER:root}:${MYSQL_PASSWORD:root123456}@tcp(${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306})/${MYSQL_DATABASE:zero_demo}?charset=utf8mb4&parseTime=true&loc=Local

Cache:
  - Host: ${REDIS_HOST:127.0.0.1}:${REDIS_PORT:6379}

Telemetry:
  Name: product.rpc
  Endpoint: ${JAEGER_ENDPOINT:127.0.0.1:4317}
  Sampler: ${JAEGER_SAMPLER:1.0}
  Batcher: otlpgrpc

Prometheus:
  Host: ${PROMETHEUS_HOST:0.0.0.0}
  Port: ${PRODUCT_RPC_PROM_PORT:9104}
  Path: /metrics